version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5436:5432'
    volumes:
      - db:/var/lib/postgresql/data

      - type: bind
        source: ./data/data.ndjson.gz
        target: /etc/data.ndjson.gz


volumes:
  db:
    driver: local